config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :users, only: %i[ index show ]

  resources :posts do
    resources :comments
  end

  put "posts/:id/like", to: "posts#like", as: "like"
  delete "posts/:id/like", to: "posts#unlike", as: "unlike"


  put "users/send_request/:following_id", to: "users#send_request", as: "send_follow_request"
  put "users/approve_request/:follower_id", to: "users#approve_request", as: "approve_follow_request"
  delete "users/reject_request/:follower_id", to: "users#reject_request", as: "reject_follow_request"




  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id", inverse_of: :posts
  has_many :comments, dependent: :destroy, inverse_of: :post
  has_many :likes, inverse_of: :post

  validates :content, :title, presence: true

  def count_likes
    self.likes.count
  end

  def add_like(user_id)
    self.likes.build(user_id: user_id)
    self.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy like unlike]
  def index
    @accepted_followers = current_user.followers
    @accepted_followings = current_user.followings

    @user_posts = current_user.posts
    @follower_posts = @accepted_followers.each_with_object([]) { |follower, results| results << follower.posts }
    @following_posts = @accepted_followings.each_with_object([]) { |following, results| results << following.posts }
    @feed = [ @user_posts, @follower_posts, @following_posts ].flatten.sort_by { |post| post.created_at }.reverse
  end

  def show
    @likes_count = @post.count_likes
  end

  def new
    @post = Post.new
  end

  def create
    @author = current_user
    @post = Post.new(post_params)
    @post.author = @author

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to root_path, status: :see_other, notice: "Post was successfuly deleted!"
  end

  def like
    @post.add_like(current_user.id)
    redirect_to @post
  end

  def unlike
    @like = @post.likes.find_by(user_id: current_user.id)
    @like.destroy! unless @like.nil?
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:content, :title, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form|%>
  <%if post.errors.any? %>
    <div>
      <h2> <%= pluralize(post.errors.count, "error")%> prohibited this post from being saved: </h2>
      <ul>
        <% post.errors.each do |error|%>
          <li> <%= error.full_message %></li>
        <%end%>
      </ul>
    </div>
  <%end%>

  <div>
    <%= form.label :title%><br>
    <%= form.text_field :title%>
  </div>

  <div>
    <%= form.label :content%><br>
    <%= form.text_area :content%>
  </div>

  <div>
    <%= form.submit%>
  </div>
<%end%>

app/views/posts/_post.html.erb
<div>
  <h3>
    <strong><%= post.title %></strong>
  </h3>

  <p>
    <%= post.content%>
  </p>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this Post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<h1>Posts</h1>
<br>
<div>
  <% @feed.each do |post|%>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <%end%>
</div>

<div>
  <%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1> New post </h1>

<%= render "form", post: @post%>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%=  render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>


  <%= button_to "Delete this post", @post, method: :delete %>
</div>


<div>
  <p>
   <%= button_to 'Like', like_path(@post), method: :put %> | <%= button_to 'Unlike', unlike_path(@post), method: :delete %>
  </p>

  <h2><Strong>Likes</strong></h2>
  <p><%= pluralize(@likes_count, "like" )%></p>

</div>


<h2> <strong> Add comment: </strong></h2>
<div>
  <%= render "comments/form", post: @post%>
</div>

<div>
  <h2> <strong> Comments: </strong></h2>
    <%= render(partial: "comments/comment", collection: @post.comments) || 'There are no comments yet'%>
</div>